### ISSUE TITLE
Privacy implications?

### ISSUE THREAD

**Issue by chaals** [w3c/magnetometer#1]
The fact that surrounding devices affect magnetic field may be an issue specific to this interface - in particular in providing location information for a previously calibrated area, or one in which a specific field pattern is created.

**Comment by anssiko** [comment]
@lknik @alexshalamov can you investigate whether this should be noted in the spec, and see if appropriate mitigations and guidance to implementers are in place.

**Comment by alexshalamov** [comment]
@anssiko We have identified similar attack vectors in [design document](https://docs.google.com/document/d/1Ml65ZdW5AgIsZTszk4mD_ohr40pcrdVFOIf0ZtWxDv0/edit#heading=h.lmg4m6asf9b4), need to think what mitigation strategies are applicable or whether we need to add new ones.

**Comment by anssiko** [comment]
@chaals, submitted a PR https://github.com/w3c/magnetometer/pull/34 to fix this issue. PTAL.

**Comment by anssiko** [comment]
@chaals, we landed https://github.com/w3c/magnetometer/commit/4c11c300c958e5094fd28f5377a73f89cb3decf6 to address this issue. If you have further comments or would like to amend the [Security and Privacy Considerations] section, please let us know.

Thank you for reviewing this specification, we appreciate your input.

[Security and Privacy Considerations]: https://w3c.github.io/magnetometer/#security-and-privacy

**Comment by chaals** [comment]
@anssiko thanks. This is a big improvement. I think this is basically enough for now, although I may submit a PR that gives a small editorial tweak to clarify that there is important information in the generic API spec, if I get around to it...

**Comment by lknik** [comment]
Hello,

Yeah this looks fine. I'm working on broader aspects but at the moment reliably can't tell when I finish.
