### ISSUE TITLE
Add use-cases and requirements section

### ISSUE THREAD

**Issue by alexshalamov** [w3c/magnetometer#24]
Would be nice to add use-cases section, I have few in mind:

- Metal detector web app
- Providing input using magnet button for VR enclosures (e.g., vrbutton.appspot.com)
- User-specific manual fusion with other low-level sensors

**Comment by riju** [comment]
>Providing input using magnet button for VR enclosures (e.g., vrbutton.appspot.com)
 https://bugs.chromium.org/p/chromium/issues/detail?id=445926

**Comment by riju** [comment]
Indoor Navigation System may use magnetometer on mobile phones. For example, IndoorAtlas (http://www.indooratlas.com/how-it-works/)
Use cases (Proximity Advertising, Way-finding in malls or airports Geo-Fencing, etc)

**Comment by alexshalamov** [comment]
Calculating compass heading is another simple use-case
