### ISSUE TITLE
Update spec status

### ISSUE THREAD

**Issue by rakuco** [w3c/magnetometer#58]
This was discussed in [TPAC 2021](https://www.w3.org/2021/10/29-dap-minutes.html#t08):

> RESOLUTION: Update Status of the Document to indicate Magnetometer is looking for developer feedback and high value use cases

**Comment by anssiko** [comment]
@rakuco, please feel free to share any other resources useful to web developers in https://github.com/w3c/magnetometer/issues/59. For example, some information on device support across OSes might help developers interested in this API.

**Comment by Zibri** [comment]
I enabled the API but I think the magnetometer api should be like the movement (accelerometer/gyro) api.

and it need at least 60 updates per second (like the other APIs) to be useful for a wider range of application aside from finding metals and "north".

**Comment by anssiko** [comment]
@Zibri thanks for your feedback. I followed up in https://github.com/w3c/magnetometer/issues/59#issuecomment-1399608216 (no worries for commenting in this PR first!).
