### ISSUE TITLE
Who is you, we, etc.?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/magnetometer#7]
> To determine true north heading, add or subtract the appropriate declination angle.

Who should add/subtract the declination angle? The user agent? The developer? Won't hardware handle this?

**Comment by marcoscaceres** [comment]
Same with:
> You can get real time value for magnetic declination from this website.

Who is "you" in the above?

**Comment by marcoscaceres** [comment]
Same with:
> we need to apply various tilt compensation techniques for which we need the a 3-axis accelerometer.

Who is "we"?

**Comment by anssiko** [comment]
Thanks, those were unclear indeed. Other than the last one had been fixed in a rounds of spec changes. The latest was just fixed in https://github.com/w3c/magnetometer/commit/a5a1a43eb9d7b168fbeec61047895a3561d7e104.
